app/accounts/urls.py
from django.conf.urls import url,include
from . import views
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm,password_reset_complete


app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$',views.signup_view, name="signup"),
    url(r'^login/$',views.login_view, name="login"),
    url(r'^logout/$',views.logout_view, name="logout"),
    url(r'^profile/$',views.profile_view, name="profile"),
    url(r'^profile/(?P<pk>\d+)/$', views.profile_view, name='view_profile_with_pk'),
    #url(r'^profile/edit/$',views.edit_user, name="edit_profile"),
    url(r'^my-profile/$',views.my_profile_view, name="my-profile"),
    url(r'^my-profile/(?P<pk>\d+)/$', views.my_profile_view, name='view_my-profile_with_pk'),
    #url(r'^profile/create-review/$',views.reviews_create, name="create-review"),
    #url(r'^profile/reviews/$',views.reviews, name="reviews"),
    #url(r'^my-profil/reviews/$', views.reviews, name='reviews_with_pk'),
    url(r'^my-profile/update/$', views.edit_user, name='account_update'),

    url(r'^my-profile/photo-update/$', views.edit_photo, name='photo_update'),
    url(r'^change-password/$',views.change_password_view, name="change_password"),
    url(r'^reset-password/$', password_reset , name="password_reset"),
    url(r'^reset-password/done/$', password_reset_done, name="password_reset_done"),
    url(r'^reset-password/confirm/$(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
     password_reset_confirm, name="password_reset_confirm"),
    url(r'^reset-password/complete/$', password_reset_complete, name="password_reset_complete"),


]

app/app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^postman/', include('postman.urls', namespace='postman')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    url(r'^about/$',views.about),
    url(r'^$',article_views.article_list, name = "home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/articles/urls.py
from django.conf.urls import url
from . import views
from .forms import CreatePosts , PickDrop
from .views import PostCreateWizard

app_name = 'articles'

urlpatterns = [
    url(r'^$',views.article_list, name = "list"),
    url(r'^create/$',PostCreateWizard.as_view([CreatePosts, PickDrop]), name="create"),
    url(r'^(?P<id>\d+)/$', views.article_detail, name="detail"),
    url(r'^(?P<id>\d+)/delete/$',views.article_delete, name = "delete"),
    url(r'^filter/$',views.filter, name = "filter"),
    url(r'^pickup-detail/(?P<id>\d+)/$', views.pickup_detail, name="pickupdetail"),
    url(r'^myposts/$',views.my_posts, name = "myposts"),
    #url(r'^messages/$',views.IndexView, name = "messages"),
]

app/postman/urls.py
from __future__ import unicode_literals
from django.conf import settings
from django.conf.urls import url
from django.views.generic.base import RedirectView
from . import views
from django.core.urlresolvers import reverse_lazy
from django.conf.urls import url
from django import VERSION
if VERSION < (1, 10):
    from django.core.urlresolvers import reverse_lazy
else:
    from django.urls import reverse_lazy
if getattr(settings, 'POSTMAN_I18N_URLS', False):
    from django.utils.translation import pgettext_lazy
else:
    def pgettext_lazy(c, m): return m

from .views import (InboxView, SentView, ArchivesView, TrashView,
        WriteView, ReplyView, MessageView, ConversationView,
        ArchiveView, DeleteView, UndeleteView, MarkReadView, MarkUnreadView)


app_name = 'postman'
urlpatterns = [


    #url(r'^inbox/?$',views.InboxView, name='inbox'),
    url(pgettext_lazy('postman_url', r'^inbox/(?:(?P<option>m)/)?$'), InboxView.as_view(), name='inbox'),
    url(pgettext_lazy('postman_url', r'^sent/(?:(?P<option>m)/)?$'), SentView.as_view(), name='sent'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^archives/(?:(?P<option>m)/)?$'), ArchivesView.as_view(), name='archives'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^trash/(?:(?P<option>m)/)?$'), TrashView.as_view(), name='trash'),
    url(pgettext_lazy('postman_url', r'^write/(?:(?P<recipients>[^/#]+)/)?$'), WriteView.as_view(), name='write'),
    #url(pgettext_lazy('postman_url', r'^messageme/(?:(?P<recipients>[^/#]+)/)?$'), MessageMeView.as_view(), name='messageme'),
    url(pgettext_lazy('postman_url', r'^reply/(?P<message_id>[\d]+)/$'), ReplyView.as_view(), name='reply'),
    url(pgettext_lazy('postman_url', r'^view/(?P<message_id>[\d]+)/$'), MessageView.as_view(), name='view'),
    # Translators: 't' stands for 'thread'
    url(pgettext_lazy('postman_url', r'^view/t/(?P<thread_id>[\d]+)/$'), ConversationView.as_view(), name='view_conversation'),
    url(pgettext_lazy('postman_url', r'^archive/$'), ArchiveView.as_view(), name='archive'),
    url(pgettext_lazy('postman_url', r'^delete/$'), DeleteView.as_view(), name='delete'),
    url(pgettext_lazy('postman_url', r'^undelete/$'), UndeleteView.as_view(), name='undelete'),
    url(pgettext_lazy('postman_url', r'^mark-read/$'), MarkReadView.as_view(), name='mark-read'),
    url(pgettext_lazy('postman_url', r'^mark-unread/$'), MarkUnreadView.as_view(), name='mark-unread'),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('postman:inbox'), permanent=True)),


]

app/articles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from geoposition.fields import GeopositionField
from django.contrib.admin.widgets import AdminDateWidget






class Article(models.Model):
    title = models.CharField(max_length = 100)
    pickup = GeopositionField()
    dropat = GeopositionField()
    description = models.TextField('Description')
    date = models.DateTimeField(auto_now_add = True)
    worth = models.IntegerField('worth($)',default=0)
    image = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default= None, null=True)
    phone = models.IntegerField(default=0 )
    #deliver_on = models.TimeField(auto_now_add = False, default= None, null=True)





    def __str__(self):
        return self.title


    def snippet(self):
        return self.description[:70]+ '...'

    def get_absolute_url(self):
        return reverse("articles:detail", kwargs ={"id": self.id})







class PointOfInterest(models.Model):
    address = models.CharField(max_length=100)
    position = GeopositionField()

    def get_absolute_url_map(self):
        return reverse("articles:map", kwargs ={"id": self.id})

app/articles/templates/articles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from geoposition.fields import GeopositionField
from django.contrib.admin.widgets import AdminDateWidget






class Article(models.Model):
    title = models.CharField(max_length = 100)
    pickup = GeopositionField()
    dropat = GeopositionField()
    description = models.TextField('Description')
    date = models.DateTimeField(auto_now_add = True)
    worth = models.IntegerField('worth($)',default=0)
    image = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default= None, null=True)
    phone = models.IntegerField(default=0 )
    





    def __str__(self):
        return self.title


    def snippet(self):
        return self.description[:70]+ '...'

    def get_absolute_url(self):
        return reverse("articles:detail", kwargs ={"id": self.id})







class PointOfInterest(models.Model):
    address = models.CharField(max_length=100)
    position = GeopositionField()

    def get_absolute_url_map(self):
        return reverse("articles:map", kwargs ={"id": self.id})

app/articles/forms.py
from django import forms
from django.db import models
from . import models
from .models import Article
from .models import PointOfInterest
from django.contrib.admin.widgets import AdminDateWidget
from django.forms.fields import DateField




class CreatePosts(forms.ModelForm):

    deliver_on = forms.DateField(widget = forms.SelectDateWidget())

    class Meta:
        model = models.Article
        fields = ['title', 'description',
                  'image', 'phone','worth','deliver_on',]

#    def save():

#        deliver_on = self.cleaned_data['deliver_on']


class PickDrop(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['pickup', 'dropat',]






class GetLoc(forms.ModelForm):
    class Meta:
        model = models.PointOfInterest
        fields = ['address','position',]

app/articles/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect ,get_object_or_404
from django.db.models import Q
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms
from .models import Article
from .models import PointOfInterest
from .forms import GetLoc , CreatePosts , PickDrop
from .filters import ArticleFilter
from formtools.wizard.views import SessionWizardView
from django.views.generic import TemplateView
from app import settings
from django.core.files.storage import FileSystemStorage
import os
from decimal import Decimal, DecimalException
from django.views import generic
from accounts.models import UserProfile
from django.contrib.auth.models import User








def article_list(request):
    articles = Article.objects.all().order_by('date');
    pk = request.user.pk


    query = request.GET.get("q")
    if query:
        articles = articles.filter(
                                Q(title__icontains = query)|
                                Q(description__icontains = query)|
                                Q(worth__icontains = query)
                                    ).distinct()
    return render(request, 'articles/article_list.html',{'articles':articles})

@login_required(login_url = "/accounts/login/")
def filter(request):
    article_list = Article.objects.all()
    article_filter = ArticleFilter(request.GET, queryset=article_list)
    return render(request,'articles/article_filter.html', {'filter': article_filter})


@login_required(login_url = "/accounts/login/")
def article_detail(request, id=None):
    article = get_object_or_404(Article, id=id)
    return render(request, 'articles/article_detail.html',{ 'article':article })




FORMS = [("step1", forms.CreatePosts),
         ("step2", forms.PickDrop)
         ]

TEMPLATES = {"0": "articles/article_create.html",
             "1": "articles/location_create.html"
            }



class PostCreateWizard(SessionWizardView):
    instance = None

    file_storage = FileSystemStorage(location=os.path.join(settings.MEDIA_ROOT, 'media'))

    def get_template_names(self):
        return [TEMPLATES[self.steps.current]]

    #Returns an object which will be passed to the form for `step`
    #as `instance`. If no instance object was provided while initializing
    #the form wizard, None will be returned

    def get_form_instance( self, step ):
        if self.instance is None:
            self.instance = Article()
        return self.instance


    def done(self, form_list, **kwargs):

        self.instance.author = self.request.user

        self.instance.save()
        return redirect('articles:list')






def article_delete(request, id=None):
    article = get_object_or_404(Article, id=id)
    article.delete()
    return redirect('articles:list')


def pickup_create(request):
    if request.method == 'POST':
        form = forms.PickDrop(request.POST, request.FILES)
        if form.is_valid():
            #save post to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.PickDrop()
    return render(request, 'articles/location_create.html', {'form': form})


#def pickup_list(request):
#    pickups = PointOfInterest.objects.all()
    #return render(request, 'poi_list.html', {'pois': pois})


def pickup_detail(request, id=None):
    pick = get_object_or_404(Article, id=id)
    return render(request, 'articles/location_pickup_detail.html',{ 'pick':pick })


@login_required(login_url = "/accounts/login/")
def calander(request):

    if request.method == 'POST':
        form = forms.TestCal(request.POST, request.FILES)
        if form.is_valid():
            #save post to db
            instance = form.save(commit=False)
            instance.author = id.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.TestCal()
    return render(request, 'articles/calander.html', {'form': form})



@login_required(login_url = "/accounts/login/")
def my_posts(request):

    #if request.author.is_authenticated():

    articles = Article.objects.filter(author=request.user);
    return render(request, 'articles/my_posts.html',{ 'articles':articles })

app/articles/templates/articles/article_create.html
{% extends 'base_layout.html'%}
{% load i18n %}


{% block content%}
    <div class="create-list">

        <h2>Make a New Post</h2>
        <p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>

        <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data" >

            {% csrf_token%}
            {{ wizard.management_form }}
            {% if wizard.form.forms %}

                {{ wizard.form.management_form }}
                {% for form in wizard.form.forms %}
                    {{ form }}
                {% endfor %}
            {% else %}
                {{ wizard.form }}
            {% endif %}
            {% if wizard.steps.prev %}

        <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">{% trans "first step" %}</button>
        <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">{% trans "prev step" %}</button>
        {% endif %}
        <input type="submit" value="{% trans "Next >" %}"/>


        </form>
    <div/>
{% endblock%}

app/articles/templates/articles/article_detail.html
{% extends 'base_layout.html'%}
{% load postman_tags %}
{% block content %}
<div class="article-detail">
    <div class="article-d">
        <h9>{{ article.title }}</h9>
        <h3>Description of service <br><br>{{ article.description }}</h3>
        <h7>${{article.worth}}</h7>

        <h4><li><a href="https://maps.google.com/?q={{article.pickup}}">Pick</a></li></h4>
        <h6>Deliver on <br><br>{{ article.deliver_on }}</h6>
        <h5><li><a href="https://maps.google.com/?q={{article.dropat}}">Drop</a></li></h5>
        <h23 class="author">added by<a href="{% url 'accounts:view_profile_with_pk' pk=article.author.pk%}">{{article.author.username}}</a></h23>
        <h8> {{article.thumb.url}}</h8>
        <br>
        <h19><li><a href="{% url 'postman:write'%}">Message me</a></li></h19>

        <br>
        <h13> Published {{ article.date }}</h13>
        <br>
        <div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/"
             data-layout="button" data-size="small" data-mobile-iframe="true"><a target="_blank"
             href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse"
             class="fb-xfbml-parse-ignore">Share</a></div>

        <div class="container">
            <div class="fa fa-whatsapp"></div>
        </div>

</div>
{% endblock %}

app/articles/templates/articles/article_filter.html
{% extends 'base_layout.html'%}

{% block content %}
<div class="new-post">
<li><a href="{% url 'articles:create' %}"class="highlight">+</a></li>
</div>
    <div class="filter-article">

    <form method="get">
    {{ filter.form.as_p }}
    <button type="submit" name="filter">Filter</button>
  </form>
  <ul>
  </div>
  <div class="articles">
      {% for article in filter.qs %}
          <div class="article">
              <h2><a href="{{ article.get_absolute_url}}">{{article.title}}</a></h2>
              <h10>{{article.snippet}}</h10>
              <h11>{{article.date}}</h11>
              <br>
              <h12>${{article.worth}}</h12>

              <h15 class="author">added by<a href="{% url 'accounts:view_profile_with_pk' pk=article.author.pk%}">{{article.author.username}}</a></h15>

              <h16><a href="{{ article.get_absolute_url}}">see details</a></h16>
          </div>
        {% endfor %}
     </div>
{% endblock%}

app/articles/templates/articles/article_list.html
{% extends 'base_layout.html'%}

{% block content %}


    <div class="new-post">
    <li><a href="{% url 'articles:create' %}"class="highlight">+</a></li>
    </div>
    <div class="articles">
        {% for article in articles %}
            <div class="article">
                <h2><a href="{{ article.get_absolute_url}}">{{article.title}}</a></h2>
                <h10>{{article.snippet}}</h10>
                <h11>{{article.date}}</h11>
                <br>
                <h12>${{article.worth}}</h12>

                <h15 class="author">added by<a href="{% url 'accounts:view_profile_with_pk' pk=article.author.pk%}">{{article.author.username}}</a></h15>

                <h16><a href="{{ article.get_absolute_url}}">see details</a></h16>
            </div>



        {% endfor %}
{% endblock%}

app/articles/templates/articles/location_create.html
<!DOCTYPE>
{% load i18n %}

{% block content%}
<h1>PICK</h1>
<p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>

<form method="POST" action="{% url "articles:create" %}">{% csrf_token %}
    {{ wizard.management_form }}


    {{ wizard.form.media }}
    {{ wizard.form.as_p }}
    {% if wizard.steps.prev %}
    <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">{% trans "< Back" %}</button>
    <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">{% trans "prev step" %}</button>
    {% endif %}
    <input type="submit" value="{% trans "Submit" %}"/>
</form>
{% endblock %}

app/articles/templates/articles/location_pickup_detail.html
<!DOCTYPE>

{% load i18n %}

{% block content%}

<div class="pickup-detail">

    <h1>PicpUp Details</h1>

    <h22>{{ pick.pickup }}</h22>
    <li><a href="https://maps.google.com/?q={{ pick.pickup }}">test</a></li>
    {{ pick.media }}
    {{ pick.as_p }}
</div>
{% endblock %}

app/articles/templates/articles/my_posts.html
{% extends 'base_layout.html'%}

{% block content %}

    <h1>POSTS</h1>
    <div class="search-bar">
        <form  method='GET' action="">
            <input type="text" name="q" placeholder="Search for details" value="{{ request.GET.q}}"/>
            <input type="submit"  value="Search">
        </form>
    </div>
    <div class="new-post">
    <li><a href="{% url 'articles:create' %}"class="highlight">+</a></li>
    </div>
    <div class="articles">
        {% for article in articles %}
            <div class="article">
                <h2><a href="{{ article.get_absolute_url}}">{{article.title}}</a></h2>
                <h10>{{article.snippet}}</h10>
                <h11>{{article.date}}</h11>
                <br>
                <h12>${{article.worth}}</h12>
                <h15 class="author">added by {{article.author.username}}</h15>
                <h16><a href="{{ article.get_absolute_url}}">see details</a></h16>
            </div>
        {% endfor %}
{% endblock%}