app/accounts/urls.py
from django.conf.urls import url,include
from . import views
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm,password_reset_complete


app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$',views.signup_view, name="signup"),
    url(r'^login/$',views.login_view, name="login"),
    url(r'^logout/$',views.logout_view, name="logout"),
    url(r'^profile/$',views.profile_view, name="profile"),
    url(r'^profile/(?P<pk>\d+)/$', views.profile_view, name='view_profile_with_pk'),
    #url(r'^profile/edit/$',views.edit_user, name="edit_profile"),
    url(r'^my-profile/$',views.my_profile_view, name="my-profile"),
    url(r'^my-profile/(?P<pk>\d+)/$', views.my_profile_view, name='view_my-profile_with_pk'),
    #url(r'^profile/create-review/$',views.reviews_create, name="create-review"),
    #url(r'^profile/reviews/$',views.reviews, name="reviews"),
    #url(r'^my-profil/reviews/$', views.reviews, name='reviews_with_pk'),
    url(r'^my-profile/update/$', views.edit_user, name='account_update'),

    url(r'^my-profile/photo-update/$', views.edit_photo, name='photo_update'),
    url(r'^change-password/$',views.change_password_view, name="change_password"),
    url(r'^reset-password/$', password_reset , name="password_reset"),
    url(r'^reset-password/done/$', password_reset_done, name="password_reset_done"),
    url(r'^reset-password/confirm/$(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
     password_reset_confirm, name="password_reset_confirm"),
    url(r'^reset-password/complete/$', password_reset_complete, name="password_reset_complete"),


]

app/app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^postman/', include('postman.urls', namespace='postman')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    url(r'^about/$',views.about),
    url(r'^$',article_views.article_list, name = "home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals,division

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating
from app import settings
from star_ratings.models import AbstractBaseRating
from django.core.urlresolvers import reverse





class UserProfile(models.Model):


    user = models.OneToOneField(User, related_name='user', null=True, blank=True)
    image = models.ImageField(upload_to='profile_image', blank=False, null=True)
    phone = models.CharField(max_length=20, blank=True, default='',null=True)
    city = models.CharField(max_length=100, default='', blank=True ,null=True)
    country = models.CharField(max_length=100, default='', blank=True ,null=True)
    #date = models.DateTimeField(auto_now_add = True, null=True, blank=True,)
    #author = models.ForeignKey(User, default= None, null=True)


class Review(models.Model):

    #user = models.OneToOneField(UserProfile, related_name='profile_user', null=True, blank=True)
    user = models.ForeignKey(UserProfile, default= None, null=True)
    text = models.TextField(max_length=200, default='', blank=True ,null=True)
    date = models.DateTimeField(auto_now_add = True)
    author = models.ForeignKey(User, default= None, null=True)


    def __str__(self):
        return self.text

#    def get_absolute_url(self):
#        return reverse("accounts:reviews", kwargs ={"id": self.id})

    def get_absolute_url(self):
        return reverse("accounts:reviews_with_pk", kwargs ={"id": self.id})


def create_profile(sender, **kwargs):
    user = kwargs["instance"]
    if kwargs["created"]:
        user_profile = UserProfile(user=user)
        user_profile.save()
post_save.connect(create_profile, sender=User)

app/accounts/templates/accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals,division

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating
from app import settings
from star_ratings.models import AbstractBaseRating





class UserProfile(models.Model):


    user = models.OneToOneField(User, related_name='user', null=True, blank=True)
    image = models.ImageField(upload_to='profile_image', blank=False, null=True)
    phone = models.CharField(max_length=20, blank=True, default='',null=True)
    city = models.CharField(max_length=100, default='', blank=True ,null=True)
    country = models.CharField(max_length=100, default='', blank=True ,null=True)

class Review(models.Model):


    text = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    author = models.ForeignKey(User, default= None, null=True)


    def __str__(self):
        return self.body

    def get_absolute_url(self):
        return reverse("accounts:reviews", kwargs ={"id": self.id})




def create_profile(sender, **kwargs):
    user = kwargs["instance"]
    if kwargs["created"]:
        user_profile = UserProfile(user=user)
        user_profile.save()
post_save.connect(create_profile, sender=User)

app/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.db import models
from string import Template
from django.utils.safestring import mark_safe
from .models import UserProfile ,Review







class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class UserProfilePhoto(forms.ModelForm):
    class Meta:
        model = User
        fields = []


class CommentsForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text']


class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password',)


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password', )

app/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import (UserCreationForm,AuthenticationForm,
                                       UserChangeForm, PasswordChangeForm)
from django.contrib.auth import login,logout,authenticate,update_session_auth_hash
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.contrib.auth import update_session_auth_hash
from .models import UserProfile , Review
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import UserProfileForm , SignUpForm , UserProfilePhoto , EditProfileForm , CommentsForm
from django.forms.models import inlineformset_factory
from django.core.exceptions import PermissionDenied
from . import forms
from django.db.models import Q
from .filters import ReviewFilter , ProfileFilter
from django.contrib.auth.decorators import login_required


@login_required(login_url = "/accounts/login/")
def edit_user(request):
    pk = request.user.pk
    user = User.objects.get(pk=pk)
    user_form = UserProfileForm(instance=user)

    ProfileInlineFormset = inlineformset_factory(User, UserProfile, fields=( 'phone', 'city', 'country','image',))
    formset = ProfileInlineFormset(instance=user)

    if request.user.is_authenticated() and request.user.id == user.id:
        if request.method == "POST":
            user_form = UserProfileForm(request.POST, request.FILES, instance=user)
            formset = ProfileInlineFormset(request.POST, request.FILES, instance=user)

            if user_form.is_valid():
                created_user = user_form.save(commit=False)
                formset = ProfileInlineFormset(request.POST, request.FILES, instance=created_user)

                if formset.is_valid():
                    created_user.save()
                    formset.save()

                    return redirect('accounts:profile')

        return render(request, "accounts/account_update.html", {
            "noodle": pk,
            "noodle_form": user_form,
            "formset": formset,
        })
    else:
        raise PermissionDenied



@login_required(login_url = "/accounts/login/")
def edit_photo(request):
    pk = request.user.pk
    user = User.objects.get(pk=pk)
    user_form = UserProfilePhoto(instance=user)

    ProfileInlineFormset = inlineformset_factory(User, UserProfile, fields=( 'image',))
    formset = ProfileInlineFormset(instance=user)

    if request.user.is_authenticated() and request.user.id == user.id:
        if request.method == "POST":
            user_form = UserProfilePhoto(request.POST, request.FILES, instance=user)
            formset = ProfileInlineFormset(request.POST, request.FILES, instance=user)

            if user_form.is_valid():
                created_user = user_form.save(commit=False)
                formset = ProfileInlineFormset(request.POST, request.FILES, instance=created_user)

                if formset.is_valid():
                    created_user.save()
                    formset.save()

                    return redirect('accounts:profile')

        return render(request, "accounts/photo_update.html", {
            "noodle": pk,
            "noodle_form": user_form,
            "formset": formset,
        })
    else:
        raise PermissionDenied






def signup_view(request):

    if request.method == 'POST':
        form = SignUpForm(request.POST,request.FILES or None)
        if form.is_valid():
            form.save()
            user = request.user
            login(request, user)
            return redirect('articles:list')
    else:
        form = SignUpForm()
    return render(request,'accounts/signup.html', {'form':form})


def login_view(request):

    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            #log the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')

    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html', {'form':form})


def logout_view(request):

    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')


@login_required(login_url = "/accounts/login/")
def my_profile_view(request, pk=None ):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/my_profile.html', args)

@login_required(login_url = "/accounts/login/")
def profile_view(request, pk=None ):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profile.html', args)


#def edit_profile_view(request):

#    if request.method == 'POST':
#        form = EditProfileForm(request.POST, instance=request.user)

#        if form.is_valid():
#            form.save()
#            return redirect('accounts:profile')
#    else:
#        form = EditProfileForm(instance=request.user)
#        args = {'form':form}
#    return render(request, 'accounts/edit_profile.html', args)

@login_required(login_url = "/accounts/login/")
def change_password_view(request):

    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('accounts:profile')
        else:
            return redirect('accounts:change_password')

    else:
        form = PasswordChangeForm(user=request.user)
    return render(request, 'accounts/change_password.html', {'form':form})

@login_required(login_url = "/accounts/login/")
def reviews_create(request):
    if request.method == 'POST':
        form = forms.CommentsForm(request.POST, request.FILES)

        if form.is_valid():
            #save post to db
            instance = form.save(commit=False)
            instance.save()
    else:
        form = forms.CommentsForm()
    return render(request, 'accounts/create_review.html', {'form': form})

app/accounts/templates/accounts/account_update.html
{% extends 'base_layout.html'%}

{% block content %}
<h1>Update Your Profile </h1>
<br>
<br>

<div class="profile_update">
<form action="." method="POST" class="padding" enctype="multipart/form-data">
{% csrf_token %} {{ noodle_form.as_p }}
<div class="divider"></div>
{{ formset.management_form }}
{{ formset.as_p }}
<br>
<button type="submit" class="btn-floating btn-large waves-light waves-effect">Done</button>
history
</form>
</div>
{% endblock %}

app/accounts/templates/accounts/change_password.html
{% extends 'base_layout.html'%}

{%block content%}
<title>Profile</title>
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>
{%endblock%}

app/accounts/templates/accounts/create_review.html
{% extends 'base_layout.html'%}
{% load static from staticfiles %}

{% block content %}
    <h1>Signup</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <input type="submit"  value="Rate">
    </form>
{% endblock %}

app/accounts/templates/accounts/edit_profile.html
{% extends 'base_layout.html'%}

{%block content%}
<title>Profile</title>
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>
{%endblock%}

app/accounts/templates/accounts/login.html
{% extends 'base_layout.html'%}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{form}}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <input type="submit"  value="Login">
    </form>
{% endblock %}

app/accounts/templates/accounts/my_profile.html
{% extends 'base_layout.html'%}

{% load static from staticfiles %}

{%block content%}



<div class="profile">

    <div class="profile_pic">
        <img src="{{ user.user.image.url }}" width="20%">
            <div class="change_photo">
            <div class="text"
            <li><a href="{% url 'accounts:photo_update' %}">Update photo</a></li>
    </div>
            </div>
            </div>

        <link rel="stylesheet" href="/css/master.css">

        <div class="info">
        <p>{{ user.first_name }} {{ user.last_name }}</p>
        </div>
        <br>
        <br>
    <header>
        {% load ratings %}
                <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
                <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>


        {% ratings user %}
        <br>
        <br>
        <br>
        <li><a href=> See Reviews</a></li>
        <div class="bio">
            <br>
            <h2>Bio</h2>
            <br>
            <p>Username   : {{ user }}</p>
            <p>Lives in  : {{ user.user.city }},{{ user.user.country }}</p>
            <li><a href="{% url 'accounts:account_update' %}"> + add to your bio</a></li>
        </div>
    </header>
</div>
{%endblock%}

app/accounts/templates/accounts/photo_update.html
{% extends 'base_layout.html'%}

{% block content %}
<h1>Update Your Profile photo </h1>
<br>
<br>

<div class="profile_update">
    <div class="profile_pic">
        <img src="{{ user.user.image.url }}" width="20%">
            <div class="change_photo">
            <div class="text"
            <li><a href="{% url 'accounts:photo_update' %}">Update photo</a></li>
    </div>
            </div>
            </div>

<form action="." method="POST" class="padding" enctype="multipart/form-data">
{% csrf_token %} {{ noodle_form.as_p }}
<div class="divider"></div>
{{ formset.management_form }}
{{ formset.as_p }}
<br>
<button type="submit" class="btn-floating btn-large waves-light waves-effect">Done</button>
history
</form>
</div>
{% endblock %}

app/accounts/templates/accounts/profile.html
{% extends 'base_layout.html'%}

{% load static from staticfiles %}

{%block content%}



<div class="profile">

    <div class="profile_pic">
        <img src="{{ user.user.image.url }}" width="20%">
            <div class="change_photo">
            <div class="text"
            <li><a href="{% url 'accounts:account_update' %}">Update photo</a></li>
    </div>
            </div>
            </div>

        <link rel="stylesheet" href="/css/master.css">

        <div class="info">
        <p>{{ user.first_name }} {{ user.last_name }}</p>
        </div>
        <br>
        <br>
    <header>
        {% load ratings %}
                <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
                <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

        {% ratings user %}
        <br>
        <br>
        <br>
        <li><a href=> See Reviews</a></li>
        <div class="bio">
            <br>
            <h2>Bio</h2>
            <br>
            <p>Username   : {{ user }}</p>
            <p>Lives in  : {{ user.user.city }},{{ user.user.country }}</p>
        </div>
    </header>
</div>
{%endblock%}

app/accounts/templates/accounts/reviews.html
{% extends 'base_layout.html'%}

{% block content %}


    <div class="new-post">
    <li><a href="{% url 'accounts:create-review' %}"class="highlight">+</a></li>
    </div>
    <div class="reviews">
        {% for review in reviews %}
            <div class="review">
                <h20>{{review.text}}</h20>

                <h15 class="author">added by {{review.author.username}}</h15>
            </div>
        {% endfor %}
{% endblock%}

app/accounts/templates/accounts/signup.html
{% extends 'base_layout.html'%}

{% block content %}
    <h1>Signup</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <input type="submit"  value="Signup">
    </form>
{% endblock %}