app/accounts/urls.py
from django.conf.urls import url,include
from . import views
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm,password_reset_complete


app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$',views.signup_view, name="signup"),
    url(r'^login/$',views.login_view, name="login"),
    url(r'^logout/$',views.logout_view, name="logout"),
    url(r'^profile/$',views.profile_view, name="profile"),
    url(r'^profile/(?P<pk>\d+)/$', views.profile_view, name='view_profile_with_pk'),
    #url(r'^profile/edit/$',views.edit_user, name="edit_profile"),
    url(r'^my-profile/$',views.my_profile_view, name="my-profile"),
    url(r'^my-profile/(?P<pk>\d+)/$', views.my_profile_view, name='view_my-profile_with_pk'),
    #url(r'^profile/create-review/$',views.reviews_create, name="create-review"),
    #url(r'^profile/reviews/$',views.reviews, name="reviews"),
    #url(r'^my-profil/reviews/$', views.reviews, name='reviews_with_pk'),
    url(r'^my-profile/update/$', views.edit_user, name='account_update'),

    url(r'^my-profile/photo-update/$', views.edit_photo, name='photo_update'),
    url(r'^change-password/$',views.change_password_view, name="change_password"),
    url(r'^reset-password/$', password_reset , name="password_reset"),
    url(r'^reset-password/done/$', password_reset_done, name="password_reset_done"),
    url(r'^reset-password/confirm/$(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
     password_reset_confirm, name="password_reset_confirm"),
    url(r'^reset-password/complete/$', password_reset_complete, name="password_reset_complete"),


]

app/app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^postman/', include('postman.urls', namespace='postman')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    url(r'^about/$',views.about),
    url(r'^$',article_views.article_list, name = "home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/articles/urls.py
from django.conf.urls import url
from . import views
from .forms import CreatePosts , PickDrop
from .views import PostCreateWizard

app_name = 'articles'

urlpatterns = [
    url(r'^$',views.article_list, name = "list"),
    url(r'^create/$',PostCreateWizard.as_view([CreatePosts, PickDrop]), name="create"),
    url(r'^(?P<id>\d+)/$', views.article_detail, name="detail"),
    url(r'^(?P<id>\d+)/delete/$',views.article_delete, name = "delete"),
    url(r'^filter/$',views.filter, name = "filter"),
    url(r'^pickup-detail/(?P<id>\d+)/$', views.pickup_detail, name="pickupdetail"),
    url(r'^myposts/$',views.my_posts, name = "myposts"),
    #url(r'^messages/$',views.IndexView, name = "messages"),
]

app/templates/about.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About</title>
    </head>
    <body>
      <h1>About us</h1>
      <p>We like django</p>

    </body>
</html>

app/templates/base_layout.html
{% load static from staticfiles %}
{% load i18n static %}{% load postman_tags %}




<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Article</title>
        <link rel="stylesheet" href="{% static 'styles.css'%}">
    </head>
    <div id="sidebar">
        <div class="toggle-btn" onclick="toggleSidebar()">
            <span></span>
            <span></span>
            <span></span>
        </div>
        <ul>
            <br>

            <div class="sidebar_photo">
            <li><img src="{{ user.user.image.url }}"><a href="{% url 'accounts:my-profile' %}">{{user.first_name}}</a></li>
            </div>
            <br>
            <br>
            <li><a href="{% url 'articles:filter' %}">Home</a></li>
            {% postman_unread as unread_count %}
            <li><a href="{% url 'postman:inbox' %}">{% trans "Messages" %}{% if unread_count %} <strong>({{ unread_count }})</strong>{% endif %}</a></li>
            <li><a href="{% url 'articles:create' %}">New Post +</a></li>
            <li><a href="{% url 'articles:myposts' %}">My Posts</a></li>
            <br>
            <br>
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
            <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
        </ul>
    </div>

        <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.12';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

        <header class="Wrapper">
            <h1><a href="{% url 'home' %}"><img src="{%static 'test_logo.png'%}" alt="app"/></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated%}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" >Logout</button>
                        </form>
                    </li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="Wrapper">
        <script src="/static/toggle.js"></script>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

app/templates/homepage.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Homepage</title>
    </head>
    <body>
      <h1>This is the homepage</h1>
      <p>Welcome to App</p>

    </body>
</html>